# Generated by Django 5.1.6 on 2025-03-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
