# Generated by Django 5.1.6 on 2025-03-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0002_remove_book_published_date_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
    ]
